split scalatests

diff --git a/.github/workflows/scalatest.yml b/.github/workflows/scalatest.yml
--- a/.github/workflows/scalatest.yml
+++ b/.github/workflows/scalatest.yml
@@ -24,6 +24,8 @@ jobs:
       # Currently sbt and fakeroot are installed by default
       - name: Coursier cache
         uses: coursier/cache-action@v5
+      - name: Compile
+        run: sbt compile
       - name: run scalatest
         run: sbt "testOnly vct.*" || true
       - name: Test Report
@@ -48,6 +50,8 @@ jobs:
       # Currently sbt and fakeroot are installed by default
       - name: Coursier cache
         uses: coursier/cache-action@v5
+      - name: Compile
+        run: sbt compile
       - name: run scalatest
         run: sbt "testOnly integration.BasicTests integration.BasicSlowTests integration.BasicVerySlowTests  integration.VeymontTests integration.ProblemFailTests" || true
       - name: Test Report
@@ -72,6 +76,8 @@ jobs:
       # Currently sbt and fakeroot are installed by default
       - name: Coursier cache
         uses: coursier/cache-action@v5
+      - name: Compile
+        run: sbt compile
       - name: run scalatest
         run: sbt "testOnly integration.Generated1Tests" || true
       - name: Test Report
@@ -79,32 +85,6 @@ jobs:
         if: success() || failure()    # run this step even if previous step failed
         with:
           name: TestReport Generated1            # Name of the check run which will be created
-          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
-          reporter: java-junit
-
-  run-scalatest-generated-2:
-    runs-on: ubuntu-latest
-    environment: Default
-    steps:
-      # This should automatically cancel any previous workflows that are still
-      # running when for example new commits are pushed.
-      #- uses: technote-space/auto-cancel-redundant-workflow@v1
-      - uses: actions/checkout@v2
-      - uses: actions/setup-java@v1
-        with:
-          java-version: "11"
-      # Currently sbt and fakeroot are installed by default
-      - name: Coursier cache
-        uses: coursier/cache-action@v5
-      - name: Compile
-        run: sbt compile
-      - name: run scalatest
-        run: sbt "testOnly integration.Generated2Tests" || true
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
-        with:
-          name: TestReport Generated2            # Name of the check run which will be created
           path: '**/target/test-reports/TEST-*.xml'    # Path to test results
           reporter: java-junit
 
@@ -235,6 +215,136 @@ jobs:
         if: success() || failure()    # run this step even if previous step failed
         with:
           name: TestReport Generated slow 5            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-very-slow-1:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: Compile
+        run: sbt compile
+      - name: run scalatest
+        run: sbt "testOnly integration.GeneratedVerySlow1Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: TestReport Generated very slow 1            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-very-slow-2:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: Compile
+        run: sbt compile
+      - name: run scalatest
+        run: sbt "testOnly integration.GeneratedVerySlow2Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: TestReport Generated very slow 2            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-very-slow-3:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: Compile
+        run: sbt compile
+      - name: run scalatest
+        run: sbt "testOnly integration.GeneratedVerySlow3Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: TestReport Generated very slow 3            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-very-slow-4:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: Compile
+        run: sbt compile
+      - name: run scalatest
+        run: sbt "testOnly integration.GeneratedVerySlow4Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: TestReport Generated very slow 4            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-very-slow-5:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: Compile
+        run: sbt compile
+      - name: run scalatest
+        run: sbt "testOnly integration.GeneratedVerySlow5Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: TestReport Generated very slow 5       # Name of the check run which will be created
           path: '**/target/test-reports/TEST-*.xml'    # Path to test results
           reporter: java-junit
 
