split scalatests

diff --git a/.github/workflows/scalatest.yml b/.github/workflows/scalatest.yml
--- a/.github/workflows/scalatest.yml
+++ b/.github/workflows/scalatest.yml
@@ -10,7 +10,7 @@ on:
     branches:
       - '**'
 jobs:
-  run-scalatest:
+  run-scalatest-vct:
     runs-on: ubuntu-latest
     environment: Default
     steps:
@@ -25,7 +25,7 @@ jobs:
       - name: Coursier cache
         uses: coursier/cache-action@v5
       - name: run scalatest
-        run: sbt "test" || true
+        run: sbt "testOnly vct.*" || true
       - name: Test Report
         uses: dorny/test-reporter@v1
         if: success() || failure()    # run this step even if previous step failed
@@ -34,7 +34,7 @@ jobs:
           path: '**/target/test-reports/TEST-*.xml'    # Path to test results
           reporter: java-junit
 
-  run-scalatest-slow:
+  run-scalatest-basic-and-veymont:
     runs-on: ubuntu-latest
     environment: Default
     steps:
@@ -49,7 +49,175 @@ jobs:
       - name: Coursier cache
         uses: coursier/cache-action@v5
       - name: run scalatest
-        run: sbt "testOnly integration.BasicSlowTests" || true
+        run: sbt "testOnly integration.BasicTests integration.BasicSlowTests integration.BasicVerySlowTests  integration.VeymontTests integration.ProblemFailTests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Scalatests slow report            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-1:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: run scalatest
+        run: sbt "testOnly integration.Generated1Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Scalatests slow report            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-2:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: run scalatest
+        run: sbt "testOnly integration.Generated2Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Scalatests slow report            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-slow-1:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: run scalatest
+        run: sbt "testOnly integration.GeneratedSlow1Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Scalatests slow report            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-slow-2:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: run scalatest
+        run: sbt "testOnly integration.GeneratedSlow2Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Scalatests slow report            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-slow-3:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: run scalatest
+        run: sbt "testOnly integration.GeneratedSlow3Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Scalatests slow report            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-slow-4:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: run scalatest
+        run: sbt "testOnly integration.GeneratedSlow4Tests" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Scalatests slow report            # Name of the check run which will be created
+          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
+  run-scalatest-generated-slow-5:
+    runs-on: ubuntu-latest
+    environment: Default
+    steps:
+      # This should automatically cancel any previous workflows that are still
+      # running when for example new commits are pushed.
+      #- uses: technote-space/auto-cancel-redundant-workflow@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+      # Currently sbt and fakeroot are installed by default
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: run scalatest
+        run: sbt "testOnly integration.GeneratedSlow5Tests" || true
       - name: Test Report
         uses: dorny/test-reporter@v1
         if: success() || failure()    # run this step even if previous step failed
