slow tests

diff --git a/.github/workflows/slow-tests.yml b/.github/workflows/slow-tests.yml
--- a/.github/workflows/slow-tests.yml
+++ b/.github/workflows/slow-tests.yml
@@ -16,24 +16,24 @@ jobs:
       # running when for example new commits are pushed.
       - uses: technote-space/auto-cancel-redundant-workflow@v1
       - uses: actions/checkout@v2
-      - name: Cache SBT dependencies modules
-        uses: actions/cache@v2
-        with:
-          path: |
-            ~/.sbt
-            ~/.ivy2/cache
-            ~/.cache/coursier
-          key: ${{ runner.os }}-build-vercors-sbt-jdk11
       - uses: actions/setup-java@v1
         with:
           java-version: "11"
       # Currently sbt and fakeroot are installed by default
-      - name: Debug step 1
+      - name: Coursier cache
+        uses: coursier/cache-action@v5
+      - name: Build and package
+        run: sbt debian:packageBin universal:packageBin
+      - name: Clean up intermediate files for caching
+        # From the sbt manual, clean up any leftover intermediate files
+        # https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html
         run: |
-          printf "${JAVA_HOME}\n"
-          ls $JAVA_HOME
-          ls $JAVA_HOME/bin
-      - run: sbt debian:packageBin
+          rm -rf "$HOME/.ivy2/local" || true
+          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
+          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
+          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
+          find $HOME/.sbt                              -name "*.lock"
+
       - name: Archive VerCors .deb
         uses: actions/upload-artifact@v2
         with:
@@ -41,13 +41,8 @@ jobs:
           retention-days: 1
           path: |
             target/*.deb
-      - name: Debug step 2
-        run: |
-          printf "${JAVA_HOME}\n"
-          ls $JAVA_HOME
-          ls $JAVA_HOME/bin
 
-  slow_tests:
+  slow-tests-linux:
     needs: build
     runs-on: ubuntu-latest
     strategy:
